### ISSUE TITLE
Can't install with Node 9.2.1

### ISSUE THREAD

**Issue by mtshare** [dpa99c/cordova-check-plugins#26]
After I updated to Node 9.2.1 I can't install cordova-check-plugins anymore.
Here is the error:
```
npm ERR! path /usr/local/lib/node_modules/cordova-check-plugins/node_modules/npm/node_modules/ansistyles
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/local/lib/node_modules/cordova-check-plugins/node_modules/npm/node_modules/ansistyles' -> '/usr/local/lib/node_modules/cordova-check-plugins/node_modules/npm/node_modules/.ansistyles.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/marcocristalli-pro/.npm/_logs/2017-12-11T11_13_27_304Z-debug.log
```

**Comment by dpa99c** [comment]
It seems to work fine for me with `node@9.2.1` and `npm@5.6.0` (see console log output below).

However, a bit of Googling turns up [this related error](https://stackoverflow.com/questions/47721447/cant-install-cordova-with-npm-5-6-0). The answer suggests it may be due to using `npm@5.6.0`, so you could try downgrading to `npm@5.5.1`.

Closing this however, as I don't believe it's an issue with this package or its direct dependencies.

[console.txt](https://github.com/dpa99c/cordova-check-plugins/files/1547720/console.txt)

**Comment by gabn88** [comment]
Same issue hore. It seems that ansistyles is installed in the folder ansi-styles.
