### ISSUE TITLE
Remove only specific plugin completely from project directory

### ISSUE THREAD

**Issue by ziyaddin** [dpa99c/cordova-check-plugins#39]
Is it possible to completely remove only specific plugin from project directory? Completely means removing from `package.json` file, `config.xml` file, `plugins` directory, `www` directory, `fetch.json` file and etc so that all inconsistent states of the plugin resolves in next cordova build.

**Comment by dpa99c** [comment]
You don't need this tool to do that because the Cordova CLI will remove a single plugin:

    cordova plugin rm cordova-plugin-something

**Comment by ziyaddin** [comment]
The fact is that cordova does not always remove plugin "completely". Sometimes after removal, it re-adds the plugin by finding its remainders inside files like `fetch.json`.

**Comment by dpa99c** [comment]
While it's true that Cordova sometimes corrupts its config files, this tool simply provides a wrapper around the Cordova CLI in order to remove plugins.
To have it implement its own mechanism for plugin removal would not be worth it since any internal changes in how Cordova internally manages its plugins would break it.
